---
- hosts: k8s-master
  become: true
  vars_files:
    - vars.yml

  tasks:

  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Copy join command to local file
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="files/join-command"

  handlers:
    - name: docker status
      service: name=docker state=started
